fix uri_parser

diff --git a/izopen b/izopen
--- a/izopen
+++ b/izopen
@@ -197,7 +197,7 @@ helper_rdp() {
         frmdata=$(LANG=C yad --center --width=300 --title "Connect to remote computer" --focus-field=4 --align=right --form --field="Domain" "$domain" --field="Address" "$host" --field="Username" "$username" --field="Password":H "$password" --field="Security":CB 'rdp!tls!^nla!ext' --field="Admin Console":CHK | grep -v "WINDOW DECORATIONS RELOADED")
         [ $? != 0 ] && exit 1
         domain=$(echo $frmdata | awk 'BEGIN {FS="|" } { print $1 }')
-        address=$(echo $frmdata | awk 'BEGIN {FS="|" } { print $2 }')
+        host=$(echo $frmdata | awk 'BEGIN {FS="|" } { print $2 }')
         username=$(echo $frmdata | awk 'BEGIN {FS="|" } { print $3 }')
         password=$(echo $frmdata | awk 'BEGIN {FS="|" } { print $4 }')
         # escape all special characters in password
@@ -218,7 +218,7 @@ helper_rdp() {
       [ -n "$password" ] && helper_cmd_opts+=" -p '$password'"
       [ -n "$port" ]     && port=":$port"
 
-      helper_cmd="rdesktop ${helper_cmd_opts} ${address}${port}"
+      helper_cmd="rdesktop ${helper_cmd_opts} ${host}${port}"
       ;;
     xfreerdp)
       # FIXME: this function always use the default keyboard
@@ -238,7 +238,7 @@ helper_rdp() {
       [ ! -z "$security" ] && helper_cmd_opts+=" /sec:$security"
       [ "$console" = "TRUE" ] && helper_cmd_opts+=" /console"
 
-      helper_cmd="xfreerdp ${helper_cmd_opts} /v:${address}"
+      helper_cmd="xfreerdp ${helper_cmd_opts} /v:${host}"
       ;;
     remmina)
       helper_cmd_opts+="${helper_cmd_opts_rdp}"
@@ -252,7 +252,7 @@ helper_vnc() {
   # vnc doesn't support username and actually don't accept the password. use the gnome keyring instead for this
   #helper_cmd="vinagre $schema://$host$([ -n $port ] && echo ":$port")"
   [ -n $port ] && helper_cmd_opts+=":$port"
-  helper_cmd="$helper_cmd_vnc ${address}${helper_cmd_opts}"
+  helper_cmd="$helper_cmd_vnc ${host}${helper_cmd_opts}"
 }
 
 helper_sftp() {
@@ -435,12 +435,12 @@ open_uri() {
   
   # parse the uri
   uri_parser $uri
-#   local schema=$uri_schema
-#   local username=$uri_username
-#   local password=$uri_password
-#   local host=$uri_host
-#   local port=$uri_port
-#   local path=$uri_path
+  local schema=$uri_schema
+  local username=$uri_username
+  local password=$uri_password
+  local host=$uri_host
+  local port=$uri_port
+  local path=$uri_path
   # for safety logging create a new uri variable without the password
   [ -z "$password" ] && local uri_safe=$uri || local uri_safe="$(echo "$uri" | sed "s/:$password//g")"
   uri_unset
@@ -469,82 +469,12 @@ open_uri() {
 
       # connect to remote server
       eval "$helper_cmd"
-      [ $? != 0 ] && tail -n 30 "${izopen_log}" | sed -n "H; /^$(date '+%Y-%m-%d')/h; \${g;p;}" | LANG=C yad --center --width=1000 --height=500 --title "Connection Error" --button="Close":0 --text "Errors from ${izopen_log}" --text-info --fontname="Monospace 8" | grep -v "WINDOW DECORATIONS RELOADED"
+      [ $? != 0 ] && tail -n 30 "${izopen_log}" | sed -n "H; /^$(date '+%Y-%m-%d')/h; \${g;p;}" | LANG=C yad --center --width=1000 --height=500 --title "Connection Error" --button="Close":0 --text "Errors from ${izopen_log}" --text-info --fontname="Monospace 8"
       ;;
     *)
       echo "ERROR: invalid URI specified: $args"
       ;;
   esac
-}
-
-#      desc: set/check/sanitize/validate a URI and the gained variables
-#      args: $1
-# args desc: 'URI'
-#    return: misc variables containing the URI data
-uri_parser() {
-    # uri capture
-    uri="$@"
-    # safe escaping
-    uri="${uri//\`/%60}"
-    uri="${uri//\"/%22}"
-    local query1 query2 path1 path2
-    # extract the schema
-    protourl="$(echo $uri | grep :// | sed -e's,^\(.*://\).*,\1,g')"
-    schema="$(echo $protourl | cut -d":" -f1 )"
-    if [[ ! -z $schema ]] ; then
-      # remove the schema
-      url="$(echo ${1/$protourl/})"
-      # since kde plasma 5.16 there is a bug when specifing extra port that add ?line=PORT&column=0
-      url="$(echo $url | sed 's/?line=/:/' | sed 's/&column=0//')"
-      # extract the user (if any)
-      login="$(echo $url | grep @ | cut -d@ -f1)"
-      username="$(echo $login | cut -d: -f1)"
-      password="$(echo $login | grep : | cut -d: -f2)"
-      password="$(echo "$password" | sed 's/!/\\!/g' | sed 's/'\''/\\'\''/g')"
-      # extract the host
-      port="$(echo ${url/"$login"@/} | cut -d/ -f1)"
-      host="$(echo ${port} | cut -d: -f1)"
-      # by request - try to extract the port
-      port="$(echo $port | grep ":" | sed -e 's,^.*:,:,g' -e 's,.*:\([0-9]*\).*,\1,g' -e 's,[^0-9],,g')"
-      # extract the uri (if any)
-      resource="/$(echo $url | grep / | cut -d/ -f2-)"
-    else
-      url=""
-      login=""
-      username=""
-      password=""
-      host=""
-      port=""
-      resource=$1
-    fi
-    # extract the path (if any)
-    path1="$(echo $resource | grep ? | cut -d? -f1 )"
-    path2="$(echo $resource | grep \# | cut -d# -f1 )"
-    path=$path1
-    if [[ -z $path ]] ; then path=$path2 ; fi
-    if [[ -z $path ]] ; then path=$resource ; fi
-    # extract the query (if any)
-    query1="$(echo $resource | grep ? | cut -d? -f2-)"
-    query2="$(echo $query1 | grep \# | cut -d\# -f1 )"
-    query=$query2
-    if [[ -z $query ]] ; then query=$query1 ; fi
-    # extract the fragment (if any)
-    fragment="$(echo $resource | grep \# | cut -d\# -f2 )"
-    url="$protourl$url"
-    if [ $debug = 2 ]; then
-      echo "url: $url"
-      echo "  schema: $schema"
-      echo "   login: $login"
-      echo "username: $username"
-      echo "password: $password"
-      echo "    host: $host"
-      echo "    port: $port"
-      echo "resource: $resource"
-      echo "    path: $path"
-      echo "   query: $query"
-      echo "fragment: $fragment"
-      echo ""
-    fi
 }
 
 #
@@ -556,7 +486,7 @@ uri_parser() {
 # [schema://][user[:password]@]host[:port][/path][?[arg1=val1]...][#fragment]
 #
 # thanks to: https://wp.vpalos.com/537/uri-parsing-using-bash-built-in-features/
-function uri_parserTEST() {
+function uri_parser() {
     # uri capture
     uri="$@"
 
@@ -565,7 +495,7 @@ function uri_parserTEST() {
     uri="${uri//\"/%22}"
 
     # top level parsing
-    pattern='^(([a-z]{3,5}):\/\/)?((([^:\/]+)(:([^@\/]*))?@)?([^:\/?]+)(:([0-9]+))?)(\/[^?]*)?(\?[^#]*)?(#.*)?$'
+    pattern='^(([a-z]{3,5}):\/\/)?((([^:]+)(:([^@\/]*))?@)?([^:\/?]+)(:([0-9]+))?)(\/[^?]*)?(\?[^#]*)?(#.*)?$'
     [[ "$uri" =~ $pattern ]] || return 1;
 
     # component extraction
@@ -661,8 +591,11 @@ Examples:
   # open a rdp connection specifing username and password:
   $ $_prog rdp:///Administrator:password@server
   
-  # open a rdp connection specifing domain, username and password and port:
+  # open a rdp connection specifing domain/username and password and port:
   $ $_prog rdp://DOMAIN/Administrator:password@server:33189
+  
+  # open a rdp connection specifing username@domain and password and port:
+  $ $_prog rdp://Administrator@example.com:password@server:33189
   
   # open a smb file share with default file manager:
   $ $_prog smb://Administrator:password@server
